version: "3.6"
services:
  nginx:
    image: brunolimame/nginx:1.15.12
    ports:
      - 80:80
    restart: always
    volumes:
      - ./:/home:rw
      - ./.docker/nginx/conf:/etc/nginx/conf.d
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    links:
      - php
    depends_on:
      - php

  php:
    image: brunolimame/php:7.2-fpm-stretch
    expose:
      - 9000
    restart: always
    volumes:
      - ./:/home:rw
      - ./.docker/php/php.ini:/usr/local/etc/php/php.ini
